title: SweetDate
description: SDIP (SweetDate Implementation Protocol)

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://github.com/SweetDate-Calendar/sd_protocol
baseurl: /sd_protocol

aux_links:
  Github Repository: https://github.com/SweetDate-Calendar/
