title: SweetDate
description: Headless Calendar with native implementations for developer satisfaction

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://sweetdate-calendar.github.io
baseurl: /sd_docs

aux_links:
  Github Repository: https://github.com/SweetDate-Calendar/
